# Generated by Django 3.2.16 on 2024-02-24 16:52

from django.db import migrations

from core.utils import remove_role_right_for_system, insert_role_right_for_system

ROLE_ID = 64
INDIGENTS_REGISTERS_RIGHTS = [131011, 131012]


def add_query_rights(apps, schema_editor):
    for right in INDIGENTS_REGISTERS_RIGHTS:
        insert_role_right_for_system(ROLE_ID, right)


def remove_query_rights(apps, schema_editor):
    for right in INDIGENTS_REGISTERS_RIGHTS:
        remove_role_right_for_system(ROLE_ID, right)


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_set_managed_to_true'),
    ]

    operations = [
        migrations.RunPython(add_query_rights, remove_query_rights),
    ]
