# Generated by Django 3.2.16 on 2024-04-16 14:03

from django.db import migrations

from core.utils import remove_role_right_for_system, insert_role_right_for_system

ROLE_ID = 64
INDIGENTS_FORMAL_SECTOR_RIGHTS = [131013, 131014]


def add_query_rights(apps, schema_editor):
    for right in INDIGENTS_FORMAL_SECTOR_RIGHTS:
        insert_role_right_for_system(ROLE_ID, right)


def remove_query_rights(apps, schema_editor):
    for right in INDIGENTS_FORMAL_SECTOR_RIGHTS:
        remove_role_right_for_system(ROLE_ID, right)


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_add_indigents_registers_rights'),
    ]

    operations = [
        migrations.RunPython(add_query_rights, remove_query_rights),
    ]
